# Generated by Django 5.2.4 on 2025-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Social', 'Social')], max_length=100, unique=True),
        ),
    ]
